### PR TITLE
Fix bug in "set" code that broke the --node flag

### PR DESCRIPTION
**Pull request by nickelization**
The unit test worked fine since I was passing in a string, but actually
we already have a typecast flag in the set spec that converts the string
to an atom for us, along with all the relevant checks to ensure it's a
valid node.

### CODE REVIEW

**Comment by ian-mi** [comment]
Only comment is that it seems that the error clause of rpc_set should no longer be necessary.

**Comment by nickelization** [comment]
Oh, of course you're right. Good catch. I gotta stop rushing out these quick fixes...

**Comment by nickelization** [comment]
@ian-mi okay, got a bit sidetracked, but that should be better now.

**Comment by jvoegele** [comment]
+1 710907d

**Comment by nickelization** [comment]
@borshop merge

**Pull request merged**
