### PR TITLE
Fix formatting for invalid command errors

### PR DESCRIPTION
**Pull request by nickelization**
This addresses issue #59

### CODE REVIEW

**Comment by macintux** [comment]
I'd much rather output the meat of the error tuple instead of the command line, or at least that's what my ticket said and I have no reason to doubt my previous self.

**Comment by nickelization** [comment]
@macintux Gotcha - I misunderstood the bug report, and didn't notice that we were building a redundant error string there. I was fixing the redundant one when I should've just been using the one passed back from clique_usage. Removed the previous commit and pushed a proper fix.

**Comment by nickelization** [comment]
@borshop merge

**Comment by bashopatricia** [comment]
Are you needing this included in Riak 2.1.2?

**Comment by macintux** [comment]
No @bashopatricia, this can wait until we tag a new release of clique. Very, very minor issue.

**Comment by bashopatricia** [comment]
@macintux According to the 2.1.1 to 2.1.2 differences report that Jon M pulled for me, this PR did get merged into 2.1.2.  This is only a heads up to you because we had a conversation above saying that this could wait until after 2.1.2.  I don't recall if there was any risk in adding this now, which is why I am tagging you.

**Comment by macintux** [comment]
No real risk, just didn’t want to place the release in any jeopardy. S’fine.

-John

**Pull request merged**
