### PR TITLE
Added a function that io_lib:format's a table and not io:format's it

### PR DESCRIPTION
**Pull request by gordonguthrie**

### CODE REVIEW

**Comment by hazen** [comment]
@gordonguthrie So what is this used for?  You just wanted to add `io_lib` versions, too?

**Comment by gordonguthrie** [comment]
Yes, riakshell collects the function returns as strings because it needs to log them (or not) into a replay log and display them (or not) in the riakshell or a bash shell.

So adding an io_lib version to clique_table seemed the right way to go...

**Comment by gordonguthrie** [comment]
```
 ./riakshell -f ../log/gg.log

Replaying "../log/gg.log"
replay (1)> select * from GeoCheckin where time > 1000001 and time < 1000010 and myfamily = 'family1' and myseries = 'seriesX';


+--------+--------+-------+-------+--------------------------+
|myfamily|myseries| time  |weather|       temperature        |
+--------+--------+-------+-------+--------------------------+
|family1 |seriesX |1000002| warm  |2.01000000000000014211e+01|
|family1 |seriesX |1000003|warmish|1.93999999999999985789e+01|
+--------+--------+-------+-------+--------------------------+
```

**Comment by andytill** [comment]
Couldn't you just call `create_table/2` it directly? It is already exported.

**Comment by gordonguthrie** [comment]
Ok, ok, I'm an idiot, I get the message ;-)

It was Friday, gies a break

**Pull request closed without merging**
