### PR TITLE
Add JSON writer #47 [JIRA: RIAK-1486]

### PR DESCRIPTION
**Pull request by nickelization**
This PR adds a JSON writer module to clique. It is only enabled at startup if the mochijson2 module can be found. It can be used by specifying --format=json on the command line.

### CODE REVIEW

**Comment by Basho-JIRA** [comment]
https://github.com/basho/clique/pull/47 

**_[posted via JIRA by Nick Marino]**_

**Comment by andrewjstone** [comment]
@nickelization This code looks great and works like a charm! The only suggestion I have is maybe adding a newline after the output. I'm not sure if that causes problems with json parsing, but it will make things look nicer on the cli or redirects to files.

**Comment by andrewjstone** [comment]
:+1: a91239d

**Comment by andrewjstone** [comment]
:+1:  a646e7f

**Comment by nickelization** [comment]
@borshop merge

**Pull request merged**
