### PR TITLE
Add ability to return a "usage" status and have clique display the

### PR DESCRIPTION
**Pull request by JeetKunDoug**
usage in case of missing/invalid flag combinations, for example.
Addresses issue #19

### CODE REVIEW

**Comment by JeetKunDoug** [comment]
Thinking about this, and wondering how to appropriately handle the more generic case of the consuming application returning clique_status:usage() from a code path where the command had flags/etc. in it. Should we do some processing of Cmd (removal of flags) at clique.erl:66?

**Comment by andrewjstone** [comment]
I think we talked about this, but clique_usage:find/1 can deal with flags fine. It does a longest match, so it will keep stripping off strings from the tail of the list until it finds a match or none is found at all.

**Comment by andrewjstone** [comment]
+1 a8d439b

**Comment by Basho-JIRA** [comment]
https://github.com/basho/clique/pull/25

This is a fix for Issue #19. 

**_[posted via JIRA by Derek Somogyi]**_

**Pull request merged**
