### PR TITLE
Add an IO group leader for use in testing scenarios.

### PR DESCRIPTION
**Pull request by seancribbs**
This is heavily based on the group leader code from riak_test. /cc @javajolt

### CODE REVIEW

**Comment by hazen** [comment]
This looks awesome, @seancribbs, and certainly nothing I would have come up with on my own!

**Comment by hazen** [comment]
:+1: 454b5ec

**Comment by andrewjstone** [comment]
Was just looking at this. I agree it looks great. Just curious how the
geometry gets used. I assume the IODevice asks the group_leader for the set
geometry?

**Comment by seancribbs** [comment]
@andrewjstone Look at the tests, they show exactly how it's used.

**Comment by andrewjstone** [comment]
Indeed. I looked too quickly. Nice work @seancribbs.

**Comment by seancribbs** [comment]
@javajolt why no "borshop merge"?

**Comment by hazen** [comment]
(facepalm) cuz I forgot?

**Pull request merged**
